$(MAIN_OBJ): $(OBJ) $(LIBS)
	$(CC) $(CCFLAGS) $(ROOT)/main.c

include $(ROOT)/shlib_operations/Makefile
include $(ROOT)/utils/Makefile
include $(ROOT)/guc/Makefile
include $(ROOT)/logger/Makefile
include $(ROOT)/memory/Makefile
include $(ROOT)/boss_operations/Makefile
include $(ROOT)/bg_worker/Makefile